# Site settings
title: Numerical methods 1

name1: Gerard Gorman
address1: Room 4.92, Royal School of Mines
email1: g.gorman@imperial.ac.uk
github_username1:  ggorman
twitter_username1: gerardjgorman

name2: Matthew Piggott
address2: Room 4.82, Royal School of Mines
email2: m.d.piggott@imperial.ac.uk
github_username2:  matt-piggott

name3: Nicolas Barral
address3: Room 4.88, Royal School of Mines
email3: n.barral@imperial.ac.uk
github_username3:  taupalosaurus


description: > # this means to ignore newlines until "baseurl:"

  This is an introductory course on numerical methods, covering topics linear algebra, root finding, differentiation and quadrature (integration).

baseurl: http://ggorman.github.io/Numerical-methods-1
production_url : http://ggorman.github.io/Numerical-methods-1

# Build settings
markdown: kramdown
